NO-ISS: Look for word-boundaried container name (#70)
#### Why I did it

Tried to save one of my build containers for use later while I rebuild
with at a different commit of FBOSS. Since I renamed the container name
by just adding a suffix, the script was detecting that there should be
the container available to run, but was failing running it due to it
searching for a substring without a word boundary.
```
anna@ds104:~/work/private-fboss$ docker ps -a | grep FBOSS
48ee3a575d01   213e78de9301                                                         "bash"                   2 days ago       Up 46 hours                                                               FBOSS_BUILD_CO
NTAINER_DEBUG
anna@ds104:~/work/private-fboss$ ./fboss/oss/scripts/nhfboss-docker-enter.py
Error response from daemon: No such container: FBOSS_BUILD_CONTAINER
Error: failed to start containers: FBOSS_BUILD_CONTAINER
Error response from daemon: No such container: FBOSS_BUILD_CONTAINER
```

#### How I did it
Updated the string check to use regex with word boundaries around the
name for the script looks for the exact container name in the docker ps
output.

#### How to verify it
Ran the script with the backed-up container name around both without
FBOSS_BUILD_CONTAINER available to ensure it starts up a new container
and with the FBOSS_BUILD_CONTAINER container available to ensure it
reenters the correct container.