NO-NOS: Add hostname package to FBOSS build container (#757)
# Summary

The build container image was missing the `hostname` utility, requiring
a manual `sudo dnf install hostname` after entering the container.

it was observed while trying to generate `asic_config_v2` ouput
```
./fboss/lib/asic_config_v2/run-helper.sh
...
...
FileNotFoundError: [Errno 2] No such file or directory: 'hostname'
```

In this PR:
- Install it at image-build time alongside the other packages.

# Test Plan
Docker container built with new image contains `hostname` utility.
When `hostname` utility is available, `asic_config_v2/run-helper.sh`
moves past this initial failure mentioned above in the description.


# Upstream required

- [x] Yes
- [ ] No

#### Upstream requirements (if PR has "Upstream Required" label)

- [x] PR title is free of sensitive information (customer names, product
codenames, internal references)