NOS-5778: Fix run_test.py regressions (#584)
# Summary

The `fboss/oss/scripts/run_scripts/run_test.py` script was broken after
recent commits. The `OPT_ARG_LIST_TESTS_FOR_FEATURE` argument was being
added twice to `sub_parser` which was causing the following error:

```
argparse.ArgumentError: argument --list-tests-for-features: conflicting option string: --list-tests-for-features
```
The duplicate `sub_parser.add_argument` call for
`OPT_ARG_LIST_TESTS_FOR_FEATURE` has been removed.

The `_get_known_bad_test_regexes()` and
`_get_unsupported_test_regexes()` functions were no longer defined but
still being referenced, which has been solved by using the
`_known_bad_test_regexes` and `_unsupported_test_regexes` variables
directly.

Lastly, calls to the `_list_tests_to_run()` function that were passing a
second boolean argument (which does not match its function signature)
have been updated to no longer have the second argument.

# Test Plan

Use the `run_test.py` script to run test cases. I ran the following
command:
```
./bin/run_test.py sai_agent --config /etc/coop/agent.conf --skip-known-bad-tests brcm/13.3.0.0_odp/13.3.0.0_odp/tomahawk5 --filter=AgentMirror*
```
which produced the following results:
```
Running all tests took 0:02:53.276536 between 2026-03-20 03:09:11.852110 and 2026-03-20 03:12:05.128646
[       OK ] warm_boot.AgentMirroringScaleTest/0.MaxMirroringTest (7773 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/0.ExceedMaxMirroringTest (7030 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/1.MaxMirroringTest (7118 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/1.ExceedMaxMirroringTest (6775 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/2.MaxMirroringTest (7083 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/2.ExceedMaxMirroringTest (6826 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/3.MaxMirroringTest (7844 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/3.ExceedMaxMirroringTest (7066 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/4.MaxMirroringTest (7117 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/4.ExceedMaxMirroringTest (6818 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/5.MaxMirroringTest (7088 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/5.ExceedMaxMirroringTest (6844 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/6.MaxMirroringTest (7815 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/6.ExceedMaxMirroringTest (6902 ms)
[       OK ] warm_boot.AgentMirroringScaleTest/7.MaxMirroringTest (7040 ms)
[       OK ] cold_boot.AgentMirroringScaleTest/7.ExceedMaxMirroringTest (6812 ms)
Summary:
   OK : 16
   FAILED : 0
   SKIPPED : 0
   TIMEOUT : 0

Test output stored at: hwtest_results_2026_Mar_20-03_12_05_AM.csv

Test result xml stored at: /home/admin/tr.xml
```

# Upstream required

- [ ] Yes
- [ ] No