NO-NOS: fix tuple typing for _run_tests (#321)
This didn't error on GE because later Python versions have lazy
evaluation of annotations, but on wdg101 with Python3.9:
```
  File "/opt/fboss/./bin/run_test.py", line 656, in TestRunner
    def _run_tests(self, tests_to_run, conf_file, args) -> tuple(list, list):
TypeError: tuple expected at most 1 argument, got 2
```