Add missing `common_cpp2` dependency to `thriftpath_test_cpp2`
Bring the cmake build in line with the BUCK build. In `thriftpath_test.thrift`
we include `fboss/agent/if/common.thrift`, and `fboss/fsdb/tests/BUCK` correctly
declares this dependency as `//fboss/agent/if:common`. The cmake build was
missing the corresponding `DEPENDS` on `common_cpp2`, causing intermittent build
failures when `common_types.h` was not yet generated:

```
In file included from /var/FBOSS/tmp_bld_dir/build/fboss/fboss/fsdb/tests/gen-cpp2/thriftpath_test_constants.cpp:8:
In file included from /var/FBOSS/tmp_bld_dir/build/fboss/fboss/fsdb/tests/gen-cpp2/thriftpath_test_constants.h:11:
/var/FBOSS/tmp_bld_dir/build/fboss/fboss/fsdb/tests/gen-cpp2/thriftpath_test_types.h:11:10: fatal error: 'fboss/agent/if/gen-cpp2/common_types.h' file not found
```