NO-NOS Alias local_rpm_repo to kernel (#1108)
# Summary

Previously Platform Manager would attempt to load the BSPs from an
explicitly named 'kernel' RPM repo, then fallback to using all repos.
This was changed in 4aa09682ce4ba86ee305010178ad6b89513cc2d5 to only
ever query the 'kernel' repo.

Distro images don't have a 'kernel' repo so loading the BSP RPM(s) would
fail like so:

```
[root@dut ~]# systemctl status platform_manager.service
× platform_manager.service - FBOSS Platform Manager
     Loaded: loaded (/usr/lib/systemd/system/platform_manager.service; enabled; preset: disabled)
     Active: failed (Result: core-dump) since Fri 2026-06-12 16:54:06 UTC; 8min ago
    Process: 1523 ExecStart=/bin/bash -c source /opt/fboss/bin/setup_fboss_env && exec /opt/fboss/bin/platform_manager --run_once=false --thrift_ssl_policy=disabled (code=dumped, signal=ABRT)
   Main PID: 1523 (code=dumped, signal=ABRT)

Jun 12 17:02:09 dut systemd[1]: Failed to start FBOSS Platform Manager.
Jun 12 17:02:12 dut systemd[1]: platform_manager.service: Start request repeated too quickly.
Jun 12 17:02:12 dut systemd[1]: platform_manager.service: Failed with result 'core-dump'.
Jun 12 17:02:12 dut systemd[1]: Failed to start FBOSS Platform Manager.
Jun 12 17:02:14 dut systemd[1]: platform_manager.service: Start request repeated too quickly.
Jun 12 17:02:14 dut systemd[1]: platform_manager.service: Failed with result 'core-dump'.
Jun 12 17:02:14 dut systemd[1]: Failed to start FBOSS Platform Manager.
Jun 12 17:02:16 dut systemd[1]: platform_manager.service: Start request repeated too quickly.
Jun 12 17:02:16 dut systemd[1]: platform_manager.service: Failed with result 'core-dump'.
Jun 12 17:02:16 dut systemd[1]: Failed to start FBOSS Platform Manager.
[root@dut ~]# cd /opt/fboss/
[root@dut fboss]# source /opt/fboss/bin/setup_fboss_env && /opt/fboss/bin/platform_manager --run_once=false --thrift_ssl_policy=disabled
I0612 17:02:58.610355  4414 PlatformNameLib.cpp:80] Getting platform name from bios using dmidecode ...
I0612 17:02:58.612698  4414 PlatformNameLib.cpp:90] Platform name inferred from bios: NH-4010-F
I0612 17:02:58.612715  4414 PlatformNameLib.cpp:92] Platform name mapped: NH4010F
I0612 17:02:58.616100  4414 ConfigValidator.cpp:920] Validating platform_manager config
I0612 17:02:58.639423  4414 ConfigValidator.cpp:971] Validating SlotTypeConfig for Slot SCM_SLOT...
I0612 17:02:58.639431  4414 ConfigValidator.cpp:971] Validating SlotTypeConfig for Slot SMB_SLOT...
I0612 17:02:58.639435  4414 ConfigValidator.cpp:1018] Validating PmUnitConfig for PmUnit SCM in Slot SCM_SLOT...
I0612 17:02:58.640077  4414 ConfigValidator.cpp:1018] Validating PmUnitConfig for PmUnit SMB in Slot SMB_SLOT...
I0612 17:02:58.662190  4414 ConfigValidator.cpp:1069] Validating Symbolic links...
I0612 17:02:58.662586  4414 ConfigValidator.cpp:1079] Validating Transceiver symbolic links...
I0612 17:02:58.662644  4414 ConfigValidator.cpp:1094] Validating xcvr LED coverage...
I0612 17:02:58.662653  4414 ConfigValidator.cpp:1099] Validating xcvr ctrl coverage...
E0612 17:02:58.662760  4414 PlatformFsUtils.cpp:144] Received error code 2 from reading from path /run/devmap/metadata/config_hash: No such file or directory
I0612 17:02:58.662765  4414 ConfigUtils.cpp:98] No stored config hash found, can't determine if config has changed
Error: No matching Packages to list
I0612 17:02:58.842154  4414 PkgManager.cpp:217] BSP Kmods nexthop_bsp_kmods-6.11.1-1.fboss.el9.x86_64-1.0.0-1 is not installed
E0612 17:02:58.842197  4414 PlatformFsUtils.cpp:144] Received error code 2 from reading from path /usr/local/nexthop_bsp/6.11.1-1.fboss.el9.x86_64/kmods.json: No such file or directory
W0612 17:02:58.927485  4414 PkgManager.cpp:396] Skipping BSP kmods unloading. Reason: /usr/local/nexthop_bsp/6.11.1-1.fboss.el9.x86_64/kmods.json doesn't exist; most likely because this is the first RPM installation.
I0612 17:02:59.012305  4414 PkgManager.cpp:470] Skipping removing old rpms. Reason: No rpms installed.
I0612 17:02:59.012329  4414 PkgManager.cpp:269] Installing BSP nexthop_bsp_kmods-6.11.1-1.fboss.el9.x86_64-1.0.0-1, Attempt #0
Error: Unknown repo: 'kernel'
I0612 17:02:59.150860  4414 PkgManager.cpp:269] Installing BSP nexthop_bsp_kmods-6.11.1-1.fboss.el9.x86_64-1.0.0-1, Attempt #1
Error: Unknown repo: 'kernel'
I0612 17:02:59.289882  4414 PkgManager.cpp:269] Installing BSP nexthop_bsp_kmods-6.11.1-1.fboss.el9.x86_64-1.0.0-1, Attempt #2
Error: Unknown repo: 'kernel'
I0612 17:02:59.431552  4414 PlatformNameLib.cpp:104] Platform name read from cache: NH4010F
E0612 17:02:59.431591  4414 StructuredLogger.cpp:73] FBOSS_ALERT Failed to install rpm (nexthop_bsp_kmods-6.11.1-1.fboss.el9.x86_64-1.0.0-1) with exit code 1 <event:unexpected_crash> <service:platform_manager> <platform:NH4010F>
F0612 17:02:59.431610  4414 Main.cpp:145] Platform Manager crashed with unexpected exception: Failed to install rpm (nexthop_bsp_kmods-6.11.1-1.fboss.el9.x86_64-1.0.0-1) with exit code 1
```

Rather than rename the local_rpm_repo to the incorrect name 'kernel' or
pollute the production Platform Manager code with OSS-specific code,
alias the local_rpm_repo in Distro Image to 'kernel' to satisfy this
need.

# Test Plan

Modified a Distro image and loaded on a dut, confirmed that platform
manager successfully:
```
[root@dut ~]# systemctl status platform_manager.service
● platform_manager.service - FBOSS Platform Manager
     Loaded: loaded (/usr/lib/systemd/system/platform_manager.service; enabled; preset: disabled)
     Active: active (running) since Fri 2026-06-12 17:41:07 UTC; 22s ago
   Main PID: 876 (platform_manage)
      Tasks: 28 (limit: 203230)
     CGroup: /system.slice/platform_manager.service
             └─876 /opt/fboss/bin/platform_manager --run_once=false --thrift_ssl_policy=disabled

Jun 12 17:41:00 localhost systemd[1]: Starting FBOSS Platform Manager...
Jun 12 17:41:07 dut systemd[1]: Started FBOSS Platform Manager.
```

# Upstream required

- [X] Yes — ensure PR title has no sensitive info; it's used as the
upstream branch + commit message unless overridden below. Jira IDs in
title are ignored.

  - [ ] Custom commit message
    ```text
    <custom commit message>
    ```
  - [X] Custom branch name
    ```text
    distro_alias_kernel_repo
    ```
  - [ ] Cherry-pick now (runs immediately; later changes must be manual)

- [ ] No