NO-NOS: fix run_test.py (#801)
# Summary
noticed 2 errors when running sai_agent tests.
first:
```
Traceback (most recent call last):
  File "/opt/fboss/./bin/run_test.py", line 2385, in <module>
    func(args)
  File "/opt/fboss/./bin/run_test.py", line 1032, in run_test
    output, results = self._run_tests(tests_to_run, conf_file, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fboss/./bin/run_test.py", line 778, in _run_tests
    disable_services(args.type)
                     ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'type'
```
then:
```
Stopping services: s, a, i, _, a, g, e, n, t, _, h, w, _, t, e, s, t, -, s, a, i, _, i, m, p, l
```

# Test Plan
`./bin/run_test.py sai_agent --filter AgentEmptyTest.CheckInit --config
/etc/coop/agent.conf --agent-run-mode mono`

# Upstream required

- [ ] Yes
- [ ] No

#### Upstream requirements (if PR has "Upstream Required" label)

- [ ] PR title is free of sensitive information (customer names, product
codenames, internal references)