NO-NOS: fix fboss log direcory creation (#657)
# Summary
platform manager was failing to start:
```
Apr 02 12:51:49 localhost systemd[1]: Starting FBOSS Platform Manager...
Apr 02 12:51:49 localhost systemd[1315]: platform_manager.service: Failed to set up standard output: Permission denied
Apr 02 12:51:49 localhost systemd[1315]: platform_manager.service: Failed at step STDOUT spawning /bin/bash: Permission denied
Apr 02 12:51:49 localhost systemd[1]: platform_manager.service: Main process exited, code=exited, status=209/STDOUT
Apr 02 12:51:49 localhost systemd[1]: platform_manager.service: Failed with result 'exit-code'.
Apr 02 12:51:49 localhost systemd[1]: Failed to start FBOSS Platform Manager.
```
because `semanage` was silently failing:
```
# semanage
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 29, in <module>
    import seobject
ModuleNotFoundError: No module named 'seobject'
```

# Test Plan
platform manager should be running after pxeboot since log directory is
properly created:
```
# ls -ldZ /var/facebook/logs/fboss
drwxr-xr-x. 1 root root system_u:object_r:var_log_t:s0 378 Apr  2 21:18 /var/facebook/logs/fboss
```

# Upstream required

- [ ] Yes
- [ ] No

#### Upstream requirements (if PR has "Upstream Required" label)

- [ ] PR title is free of sensitive information (customer names, product
codenames, internal references)